sudo: false

services:
  - docker

language: generic

script:
  - docker build -t olifre/gentoo-docker-physics.setup .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push olifre/gentoo-docker-physics.setup
